from tasks.nse_india_traded_to_delivered import NSEIndiaTradedToDelivered
from tasks.rediff_money_traded_to_delivered import RediffMoneyTradedToDelivered
from tasks.traded_to_percent_delivered import TradedToPercentDelivered