name: todo-actions

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
        
